### ISSUE TITLE
Multiple Menus

### ISSUE THREAD

**Issue by AndreSteynPersonal** [autreplanete/angular-ap-lateral-slide-menu#2]
Just want to find out if it is possible to have multiple menus using this code? 

i.e. have multiple lateral-slide-menu tags and make lateral-slide-menu-toggle open different menus

**Comment by thierryc** [comment]
I never try. But why not.  
Try it and send me your feedback.

**Comment by AndreSteynPersonal** [comment]
Been trying all day :( does not seem to be possible

**Comment by thierryc** [comment]
Ok, What do you want to do ? 
add one on the left and one on the right ?

For the moment only one can be added. I take a look into the code.
But it is not a big deal to customise the code to add this feature. 
You need to add a param to the "lateral-slide-menu" and one when you call it…

**Comment by AndreSteynPersonal** [comment]
I want to make three buttons that open three different menus on the left, but only one menu is displayed at a time

where would i add params?

**Comment by thierryc** [comment]
Not too difficult. You have many options.
One of them is : add a state to your local scope and use ng-hide, ng-show or ng-if to change the content of the menu before to open it.

**Comment by AndreSteynPersonal** [comment]
thanks, went for the ng-if option, works!

**Comment by thierryc** [comment]
Good news ! Happy Code.
